# Generated by Django 2.2 on 2022-05-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.IntegerField()),
                ('hora_data', models.DateTimeField(null=True)),
                ('painel_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='senhas.Categoria')),
                ('painel_status_senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='senhas.StatusSenha')),
                ('painel_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='senhas.Tipo')),
            ],
        ),
    ]
